CREATE TABLE `chat_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`sajuId` int,
	`role` enum('user','assistant') NOT NULL,
	`content` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `chat_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `compatibility_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`firstSajuId` int,
	`firstName` varchar(100) NOT NULL,
	`firstGender` enum('M','F') NOT NULL,
	`firstDayStem` varchar(1) NOT NULL,
	`firstDayBranch` varchar(1) NOT NULL,
	`secondSajuId` int,
	`secondName` varchar(100) NOT NULL,
	`secondGender` enum('M','F') NOT NULL,
	`secondDayStem` varchar(1) NOT NULL,
	`secondDayBranch` varchar(1) NOT NULL,
	`compatibilityScore` decimal(5,2) NOT NULL,
	`analysis` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `compatibility_analysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `saju_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(100) NOT NULL,
	`birthYear` int NOT NULL,
	`birthMonth` int NOT NULL,
	`birthDay` int NOT NULL,
	`birthHour` int NOT NULL,
	`birthMinute` int NOT NULL DEFAULT 0,
	`gender` enum('M','F') NOT NULL,
	`yearStem` varchar(1) NOT NULL,
	`yearBranch` varchar(1) NOT NULL,
	`monthStem` varchar(1) NOT NULL,
	`monthBranch` varchar(1) NOT NULL,
	`dayStem` varchar(1) NOT NULL,
	`dayBranch` varchar(1) NOT NULL,
	`timeStem` varchar(1) NOT NULL,
	`timeBranch` varchar(1) NOT NULL,
	`woodStrength` decimal(5,2),
	`fireStrength` decimal(5,2),
	`earthStrength` decimal(5,2),
	`metalStrength` decimal(5,2),
	`waterStrength` decimal(5,2),
	`tenStemsAnalysis` json,
	`majorPeriodStartAge` int,
	`majorPeriodStem` varchar(1),
	`majorPeriodBranch` varchar(1),
	`title` varchar(200),
	`memo` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `saju_analysis_id` PRIMARY KEY(`id`)
);
